name: Build Unsigned
on:
  workflow_dispatch:

jobs:
  BuildUnsigned:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon app:assembleFossRelease
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/*v7*.apk

